config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'

  get '/search' => 'static_pages#search', :as => 'search_page'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord

  def self.search
    url = 'https://mach-eight.uc.r.appspot.com'
    uri = URI(url)
    response = Net::HTTP.get(uri)
    res = JSON.parse(response)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

require 'net/http'
require 'json'

class StaticPagesController < ApplicationController
  before_action :load_json

  def index; end

  def search
    if params[:search].blank?
      redirect_to(root_path, alert: "Empty field!") and return
    else
      @parameter = params[:search].downcase
      @res.each do |value|
        player = []
        value[1].each do |val|
          player << val if val['h_in'].downcase.include? @parameter
        end
        @result = player
      end
    end
  end

  private

  def load_json
    url = 'https://mach-eight.uc.r.appspot.com'
    uri = URI(url)
    response = Net::HTTP.get(uri)
    @res = JSON.parse(response)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NBA Heights</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/index.html.erb
<br>
<br>
<br>
<%= form_tag(search_page_path, method: :get) do %>
  <%= text_field_tag(:search, params[:search]) %>
  <%= submit_tag("Search")%>
<% end %>
<br>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Height Inches</th>
    <th>Height Meters</th>
  </tr>
  <% @res.each do |value| %>
    <% value[1].each do |val| %>
      <tr>
        <td>
          <%= val['first_name'] %>
        </td>
        <td>
          <%= val['last_name'] %>
        </td>
        <td>
          <%= val['h_in'] %>
        </td>
        <td>
          <%= val['h_meters'] %>
        </td>
      </tr>

    <% end %>
  <% end %>
</table>


app/views/static_pages/search.html.erb
<h1><%= link_to 'Back to index', root_path, style: 'text-decoration: none' %></h1>
<% if @result.present? %>
<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Height Inches</th>
    <th>Height Meters</th>
  </tr>
  <% @result.each do |val| %>

    <tr>
      <td>
        <%= val['first_name'] %>
      </td>
      <td>
        <%= val['last_name'] %>
      </td>
      <td>
        <%= val['h_in'] %>
      </td>
      <td>
        <%= val['h_meters'] %>
      </td>
    </tr>


  <% end %>
</table>
<% else %>
<h1>No matched found</h1>
<% end %>